apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cluster-test
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  image: kindest/node:v1.25.0@sha256:428aaa17ec82ccde0131cb2d1ca6547d13cf5fdabcc0bbecf749baa935387cbf
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30011
    hostPort: 6379
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  labels:
    tier: backend
  image: kindest/node:v1.25.0@sha256:428aaa17ec82ccde0131cb2d1ca6547d13cf5fdabcc0bbecf749baa935387cbf
  # add a mount from <hostPath> on the host to on the node
  extraMounts:
  - hostPath: /tmp/data
    containerPath: /files
    # optional: if set, the mount is read-only.
    # default false
    # readOnly: true
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    # selinuxRelabel: false
    # optional: set propagation mode (None, HostToContainer or Bidirectional)
    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    # default None
    # propagation: HostToContainer
- role: worker
  labels:
    tier: redis
  image: kindest/node:v1.25.0@sha256:428aaa17ec82ccde0131cb2d1ca6547d13cf5fdabcc0bbecf749baa935387cbf
  extraPortMappings:
  - containerPort: 30012
    hostPort: 6380
    listenAddress: "0.0.0.0"
    protocol: TCP
  # add a mount from <hostPath> on the host to on the node
  extraMounts:
  - hostPath: /tmp/db
    containerPath: /mnt/data
    # optional: if set, the mount is read-only.
    # default false
    # readOnly: true
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    # selinuxRelabel: false
    # optional: set propagation mode (None, HostToContainer or Bidirectional)
    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    # default None
    # propagation: Bidirectional
- role: worker
  labels:
    tier: redis
  image: kindest/node:v1.25.0@sha256:428aaa17ec82ccde0131cb2d1ca6547d13cf5fdabcc0bbecf749baa935387cbf
  extraPortMappings:
  - containerPort: 30013
    hostPort: 6381
    listenAddress: "0.0.0.0"
    protocol: TCP 
  # add a mount from <hostPath> on the host to on the node
  extraMounts:
  - hostPath: /tmp/db
    containerPath: /mnt/data
    # optional: if set, the mount is read-only.
    # default false
    # readOnly: true
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    # selinuxRelabel: false
    # optional: set propagation mode (None, HostToContainer or Bidirectional)
    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    # default None
    # propagation: Bidirectional
- role: worker
  labels:
    tier: redis
  image: kindest/node:v1.25.0@sha256:428aaa17ec82ccde0131cb2d1ca6547d13cf5fdabcc0bbecf749baa935387cbf
  extraPortMappings:
  - containerPort: 30014
    hostPort: 6382
    listenAddress: "0.0.0.0"
    protocol: TCP
  # add a mount from <hostPath> on the host to on the node
  extraMounts:
  - hostPath: /tmp/db
    containerPath: /mnt/data
    # optional: if set, the mount is read-only.
    # default false
    # readOnly: true
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    # selinuxRelabel: false
    # optional: set propagation mode (None, HostToContainer or Bidirectional)
    # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    # default None
    # propagation: Bidirectional
