apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.labelSelector }}
  name: {{ .Values.service.labelSelector }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.container.containerPort }}
  selector:
    app: {{ .Values.service.labelSelector }}
  type: ClusterIP
