# Default values for packaging-be-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

namespace: default

labels: 
  labelType: backend

image:
  repository: giovannisalvatore/todoapi #<your-repository>/todoapi
  pullPolicy: Always
  tag: "1.1"

container:
  containerPort: 8080

imagePullSecrets:
  name: regCred

securityContext: 
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 2000

service:
  type: ClusterIP
  port: 8080
  labelSelector: todoapi

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 200m
     memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
